[book]
title = "B2B Go-to-Market Strategy for Découvre Bitcoin"
authors = ["Manuel Proquin"]
language = "en"
src = "."

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/man-orangepeel/DB-B2B-GTM-Strategy-2026"
additional-css = ["custom.css"]
